reorganization binaries

diff --git a/lorank8v1/init_prop b/lorank8v1/init_prop
--- a/lorank8v1/init_prop
+++ b/lorank8v1/init_prop
@@ -3,6 +3,8 @@
 # This part contains the installation of proprietary software
 
 TARGETDIR=lorank8v1
+DOGTAG=$(md5sum /etc/dogtag)
+DTSHORT=${DOGTAG:0:5}
 
 # Stop on the first sign of trouble
 set -e
@@ -14,20 +16,26 @@ then
   exit 1
 fi
 
+if [ ! -d Lorank/$TARGETDIR/$DTSHORT ]
+then
+  echo "ERROR: BBB Release not known, no initialization possible"
+  exit 1
+fi
+
 # Make necessary directories
 mkdir -p Lorank/Ngrok
 mkdir -p Lorank/Loriot
 
 # Get the ngrok binairy for remote maintenance
 pushd Lorank/Ngrok
-wget -nv -N https://github.com/Ideetron/Lorank/raw/master/lorank8v1/ngrok_latest.gz
+wget -nv -N https://github.com/Ideetron/Lorank/raw/master/$TARGETDIR/ngrok_latest.gz
 gunzip -c ngrok_latest.gz > /usr/bin/ngrok
 chmod u+x /usr/bin/ngrok
 popd
 
 # Get the Loriot packet forwarder
 pushd Lorank/Loriot
-wget -nv -N https://github.com/Ideetron/Lorank/raw/master/lorank8v1/loriot_lorank_8_iC880A_SPI_latest.tgz
+wget -nv -N https://github.com/Ideetron/Lorank/raw/master/$TARGETDIR/$DTSHORT/loriot_lorank_8_iC880A_SPI_latest.tgz
 tar xf loriot_lorank_8_iC880A_SPI_latest.tgz
 mv loriot_lorank_8_iC880A_SPI_*[^.tgz] loriot_pkt_fwd
 popd
diff --git a/lorank8v1/install b/lorank8v1/install
--- a/lorank8v1/install
+++ b/lorank8v1/install
@@ -14,6 +14,8 @@ function led_error { led_flash 0; led_flash 1; led_flash 2; led_flash 3; }
 
 VERSION=$1
 HWTARGET=lorank8v1
+DOGTAG=$(md5sum /etc/dogtag)
+DTSHORT=${DOGTAG:0:5}
 
 # Stop on the first sign of trouble
 set -e
@@ -31,12 +33,22 @@ then
   exit 1
 fi
 
+if [ ! -d Lorank/$TARGETDIR/$DTSHORT ]
+then
+  echo "ERROR: BBB Release not known, no initialization possible"
+  exit 1
+fi
+
+
 # report progress
 led_flash 0
 sleep 1
 
 # Initialize the BeagleBone for first use.
 ./Lorank/$HWTARGET/init_bbb
+
+# Perform the platform dependent initialization.
+./Lorank/$HWTARGET/$DTSHORT/init_form
 
 # Install the auxiliary software
 ./Lorank/$HWTARGET/init_aux
diff --git a/lorank8v1/upgrade b/lorank8v1/upgrade
--- a/lorank8v1/upgrade
+++ b/lorank8v1/upgrade
@@ -6,6 +6,8 @@
 
 VERSION=$1
 HWTARGET=lorank8v1
+DOGTAG=$(md5sum /etc/dogtag)
+DTSHORT=${DOGTAG:0:5}
 
 # Stop on the first sign of trouble
 set -e
@@ -20,6 +22,12 @@ fi
 if [ ! -d Lorank ]
 then
   echo "ERROR: Invalid working directory, does not contain the Lorank directory"
+  exit 1
+fi
+
+if [ ! -d Lorank/$TARGETDIR/$DTSHORT ]
+then
+  echo "ERROR: BBB Release not known, no initialization possible"
   exit 1
 fi
 
